# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Aparajithan Venkateswaran
tagline:          'Personal website'
description:      ''
url:              https://aparav.github.io
baseurl:          /

author:
  name:           'Aparajithan Venkateswaran'
  url:            https://github.com/AparaV

# Site Settings
paginate:         5
excerpt_separator: <!--excerpt_ends-->

#Plugins
whitelist:        []
plugins:             [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AparaV/aparav.github.io

# Collections
collections:
    supplements:
        output: true
    projects:
        output: false
